//图标库
export const icons=[
    {
      iconId:'1',
      iconName:'el-icon-s-tools'
    },
    {
      iconId:'2',
      iconName:'el-icon-setting'
    },
    {
      iconId:'3',
      iconName:'el-icon-delete-solid'
    },
    {
      iconId:'4',
      iconName:'el-icon-delete'
    },
    {
      iconId:'5',
      iconName:'el-icon-user-solid'
    },
    {
      iconId:'6',
      iconName:'el-icon-user'
    },
    {
      iconId:'7',
      iconName:'el-icon-upload'
    },
    {
      iconId:'8',
      iconName:'el-icon-camera-solid'
    },
    {
      iconId:'9',
      iconName:'el-icon-camera'
    },
    {
      iconId:'10',
      iconName:'el-icon-message-solid'
    },
    {
      iconId:'11',
      iconName:'el-icon-bell'
    },
    {
      iconId:'12',
      iconName:'el-icon-s-platform'
    },
    {
      iconId:'13',
      iconName:'el-icon-s-home'
    },
    {
      iconId:'14',
      iconName:'el-icon-s-shop'
    },
    {
      iconId:'15',
      iconName:'el-icon-s-comment'
    },
    {
      iconId:'16',
      iconName:'el-icon-s-custom'
    },
    {
      iconId:'17',
      iconName:'el-icon-s-check'
    },
    {
      iconId:'18',
      iconName:'el-icon-menu'
    },
    {
      iconId:'19',
      iconName:'el-icon-view'
    },
    {
      iconId:'20',
      iconName:'el-icon-date'
    },
    {
      iconId:'21',
      iconName:'el-icon-edit'
    },
    {
      iconId:'22',
      iconName:'el-icon-edit-outline'
    },
    {
      iconId:'23',
      iconName:'el-icon-folder'
    },
    {
      iconId:'24',
      iconName:'el-icon-document'
    },
    {
      iconId:'25',
      iconName:'el-icon-search'
    },
    {
      iconId:'26',
      iconName:'el-icon-monitor'
    },
    {
      iconId:'27',
      iconName:'el-icon-pie-chart'
    },
    {
      iconId:'28',
      iconName:'el-icon-data-analysis'
    },
    {
      iconId:'29',
      iconName:'el-icon-receiving'
    },
    {
      iconId:'30',
      iconName:'el-icon-office-building'
    },
    {
      iconId:'31',
      iconName:'el-icon-school'
    },
    {
      iconId:'32',
      iconName:'el-icon-chat-round'
    },
    {
        iconId:'33',
        iconName:'el-icon-chat-dot-round'
    },
    {
        iconId:'34',
        iconName:'el-icon-message'
    },
    {
        iconId:'35',
        iconName:'el-icon-place'
    },
    {
        iconId:'36',
        iconName:'el-icon-location'
    },
    {
        iconId:'37',
        iconName:'el-icon-lock'
    },
    {
        iconId:'38',
        iconName:'el-icon-unlock'
    },
    {
        iconId:'39',
        iconName:'el-icon-key'
    },
    {
        iconId:'40',
        iconName:'icon-shenji'
    },
    {
        iconId:'41',
        iconName:'icon-data'
    },
    {
        iconId:'42',
        iconName:'icon-shuju'
    },
    {
        iconId:'43',
        iconName:'icon-kaoshi'
    },
    {
        iconId:'44',
        iconName:'icon-log'
    },
    {
        iconId:'45',
        iconName:'icon-yanzhengma'
    },
    {
        iconId:'46',
        iconName:'icon-renwu'
    },
    {
        iconId:'47',
        iconName:'icon-guanli'
    },
    {
        iconId:'48',
        iconName:'icon-fuwu'
    },
    {
        iconId:'49',
        iconName:'icon-bumne2'
    },
    {
        iconId:'50',
        iconName:'icon-shenpi'
    },
    {
        iconId:'51',
        iconName:'icon-yonghuzu1'
    },
    {
        iconId:'52',
        iconName:'icon-yuyue'
    },
    {
        iconId:'53',
        iconName:'icon-chakan'
    },
    {
        iconId:'54',
        iconName:'icon-fenxi'
    },
    {
        iconId:'55',
        iconName:'icon-weihu'
    },
    {
        iconId:'56',
        iconName:'icon-tongji'
    },
    {
        iconId:'57',
        iconName:'icon-jiaose'
    },
    {
        iconId:'58',
        iconName:'icon-guanli1'
    },
    {
        iconId:'59',
        iconName:'icon-yujing'
    },
    {
        iconId:'60',
        iconName:'icon-che'
    },
    {
        iconId:'40',
        iconName:'icon-xuesheng'
    },
    {
        iconId:'40',
        iconName:'icon-jiance'
    },
    {
        iconId:'40',
        iconName:'icon-jine'
    },
    {
      iconId:'41',
      iconName:'el-icon-plus'
    },
    {
      iconId:'42',
      iconName:'el-icon-check'
    },
    {
      iconId:'43',
      iconName:'el-icon-close'
    },
  ] 